name: Build Portal
on: [ release ]
jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "linux", "darwin", "windows" ]
        arch: [ "amd64", "arm" ]
        exclude:
          - os: "darwin"
            arch: "arm"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
      - name: Build Executable
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o portal_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} -ldflags="-s -w" -v .
  release:
    needs: [build]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        run: ls -R
        with:
          files: |
            portal_darwin_amd64
            portal_darwin_arm
            portal_linux_amd64
            portal_linux_arm
            portal_windows_amd64.exe
            portal_windows_arm.exe